language: ruby
rvm:
- 2.2.1
before_script:
  - echo "GRANT ALL PRIVILEGES ON sample_test.* TO user_test@localhost IDENTIFIED BY 'pw_test' WITH GRANT OPTION;" | mysql -u root
  - bundle exec rake db:create
