default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: sample_development
  username: user_development
  password: pw_development

test:
  <<: *default
  database: sample_test
  username: user_test
  password: pw_test

production:
  <<: *default
  database: sample_production
  username: user_production
  password: pw_production
