default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  socket: <%= ENV['MYSQL_SOCKET_PATH'] %>

development:
  <<: *default
  database: sample_development
  username: user_development
  password: pw_development

test:
  <<: *default
  adapter: mysql2
  database: sample_app_test
  username: root
  encoding: utf8

production:
  <<: *default
  database: sample_production
  username: user_production
  password: pw_production
